compositionIdentifier: moneyforward.com
provider:
  baseURL: https://raw.githubusercontent.com/crossplane-contrib/%s/%s/package/crds/%s
  name: provider-upjet-aws
  version: v1.16.0
labels:
  fromCRD:
    - tags.moneyforward.com/BudgetComponent
tags:
  fromLabels:
    - tags.moneyforward.com/BudgetComponent
usePipeline: false
