compositionIdentifier: example.cloud
provider:
  baseURL: https://raw.githubusercontent.com/chen1620/%s/%s/package/crds/%s
  name: provider-aws
  version: v0.32.0
labels:
  fromCRD:
    - tags.moneyforward.com/budget-component
  common:
    commonLabelA: commonLabelAValue
    commonLabelB: commonLabelBValue
tags:
  fromLabels:
    - tags.moneyforward.com/budget-component
usePipeline: false
